### PR TITLE
Add model files, use vmaf_v0.6.1.json by default, update setup.py

### PR DESCRIPTION
**Pull request by CrypticSignal**
I've never bundled a program as a pip package before, but I believe what I have added in setup.py is correct:
```
    include_package_data=True,
    package_data={
        'ffmpeg_quality_metrics': ['vmaf_models/*.json']
    },
```
I used this as a guide: https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html

### CODE REVIEW

**Comment by slhck** [comment]
I made a few changes on top of yours, since the whole thing could be simplified a bit, selecting the default model already for the CLI options, and then just passing it on to the inner function.

Merged with a few additional code improvements.

Thanks again!

PS: There were some code style changes here and there, including trailing whitespace. I usually just run `black` over the entire file and let it do its thing.

**Comment by slhck** [comment]
Oh, I didn't see the two additional commits you created later. I added the README one via cherry picking.

The other one should have been resolved with the changes I did in the meantime.

**Comment by slhck** [comment]
You might want to check out v0.10 that I just created. The Dockerfile is now using a static build as well, with libvmaf 2.x. (I didn't know the static builds from John Van Sickle had that included.)

**Comment by CrypticSignal** [comment]
Nice! I'm not good with Docker as I have barely used it so I have a couple of questions:
1. Have you set it to add the FFmpeg executable to the PATH? If not, you should add that.
2. Is it possible to detect the operating system and download the appropriate build? Because right now, the Dockerfile is only good for Linux users.

**Comment by slhck** [comment]
Your host operating system doesn't matter in this case. It'll be portable that way and works under all operating systems.

The downloaded ffmpeg is already added to the PATH by copying it to /bin.

**Pull request closed without merging**
